#!/usr/bin/env python3
"""
SEGMENT 3 (Databricks) — close the loop: compile the bridge-generated rules
into a signed ODGS Sovereign Project and enforce a data row with the real
ODGS engine.

The Databricks bridge auto-generates two rule tiers from Unity Catalog:
  * NOT_NULL  (HARD_STOP) — from non-nullable columns   -> ENFORCED here
  * TYPE_CHECK (INFO)     — column type documentation    -> retained in the
        schema file as metadata, NOT wired into the engine (their
        `type(col)==...` expression is outside the engine's SAFE_FUNCTIONS
        vocabulary; enforcing them would be dishonest). We bind only the
        deterministic NOT_NULL HARD_STOP rules to the process.

Usage:  python3 build_and_enforce.py <ok_row.json | bad_row.json>
"""
import json, hashlib, os, sys, logging, datetime

import jwt
from cryptography.hazmat.primitives.asymmetric import ec, ed25519
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey

logging.getLogger("sovereign_git_logger").setLevel(logging.ERROR)
import odgs
from odgs import OdgsInterceptor, ProcessBlockedException

HERE = os.path.dirname(os.path.abspath(__file__))
KEYS = os.path.join(HERE, "keys")
PROJECT = os.path.join(HERE, "odgs_project")
RULES_FILE = os.path.join(HERE, "schemas/custom/snowflake_acme_finance_production_rules.json")

ISSUER = "did:web:governance.snowflake-acme.demo"
KID = "snowflake-gov-2026-01"
JWKS_URL = "http://localhost:8602/jwks.json"
PROCESS_URN = "urn:odgs:process:snowflake:write_transactions_row"
TARGET_TABLE = "PRODUCTION.FINANCE.TRANSACTIONS"
ENGINE_AUDIT_DIR = os.path.join(os.path.dirname(os.path.abspath(odgs.__file__)), "audit_logs")


def _write_pem_private(key, path):
    with open(path, "wb") as f:
        f.write(key.private_bytes(serialization.Encoding.PEM,
                serialization.PrivateFormat.PKCS8, serialization.NoEncryption()))


def build_pack():
    os.makedirs(KEYS, exist_ok=True)
    for plane in ("legislative", "judiciary", "executive"):
        os.makedirs(os.path.join(PROJECT, plane), exist_ok=True)

    ec_path = os.path.join(KEYS, "es256_pack_signing_key.pem")
    if os.path.exists(ec_path):
        ec_key = serialization.load_pem_private_key(open(ec_path, "rb").read(), password=None)
    else:
        ec_key = ec.generate_private_key(ec.SECP256R1()); _write_pem_private(ec_key, ec_path)
    jwk = json.loads(jwt.algorithms.ECAlgorithm.to_jwk(ec_key.public_key()))
    jwk.update({"kid": KID, "use": "sig", "alg": "ES256"})
    json.dump({"keys": [jwk]}, open(os.path.join(KEYS, "jwks.json"), "w"), indent=2)

    ed_path = os.path.join(KEYS, "audit_ed25519_private.pem")
    if not os.path.exists(ed_path):
        _write_pem_private(ed25519.Ed25519PrivateKey.generate(), ed_path)

    all_rules = json.load(open(RULES_FILE))["items"]
    # Enforce only deterministic NOT_NULL HARD_STOP rules on the target table.
    rules = [r for r in all_rules
             if r.get("constraint_type") == "NOT_NULL"
             and r.get("target_table") == TARGET_TABLE]
    rule_urns = [f"urn:odgs:rule:{r['rule_id']}" for r in rules]

    print(f"[compile] {len(all_rules)} rules generated by odgs-snowflake-bridge")
    print(f"[compile] binding {len(rules)} NOT_NULL HARD_STOP rules for '{TARGET_TABLE}':")
    for r in rules:
        print(f"  - {r['rule_id']}: {r['logic_expression']}  [{r['severity']}]")

    json.dump({"graph_edges": [{"source_urn": u, "target_urn": PROCESS_URN,
               "relationship": "BLOCKS_PROCESS"} for u in rule_urns]},
              open(os.path.join(PROJECT, "legislative", "ontology_graph.json"), "w"), indent=2)
    json.dump({"metadata": {"source": "snowflake"}, "items": []},
              open(os.path.join(PROJECT, "legislative", "standard_metrics.json"), "w"), indent=2)

    pack = {"pack_id": "snowflake_acme_finance_notnull", "source": {"source": "snowflake",
            "table": TARGET_TABLE}, "rules": rules}
    canonical = json.dumps(pack, sort_keys=True, separators=(",", ":"))
    file_hash = hashlib.sha256(canonical.encode()).hexdigest()
    pack["signature"] = jwt.encode({"iss": ISSUER, "file_hash": file_hash}, ec_key,
                                   algorithm="ES256", headers={"kid": KID})
    json.dump(pack, open(os.path.join(PROJECT, "judiciary", "standard_data_rules.json"), "w"), indent=2)
    print(f"\n[sign] Rule pack canonical SHA-256: {file_hash}")
    print(f"[sign] JWS (ES256, kid={KID}, iss={ISSUER}): {pack['signature'][:70]}...")

    json.dump({"contexts": [{"context_id": PROCESS_URN,
               "description": f"Writing a row to {TARGET_TABLE}", "rules": rule_urns}]},
              open(os.path.join(PROJECT, "executive", "context_bindings.json"), "w"), indent=2)
    json.dump({ISSUER: JWKS_URL}, open(os.path.join(PROJECT, "authorities.json"), "w"), indent=2)
    json.dump({"project_name": "snowflake_governance", "architecture": "sovereign_v1"},
              open(os.path.join(PROJECT, "odgs.json"), "w"), indent=2)


def last_engine_audit_entry():
    today = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d")
    path = os.path.join(ENGINE_AUDIT_DIR, f"audit_{today}.jsonl")
    lines = [ln for ln in open(path).read().splitlines() if ln.strip()]
    return json.loads(lines[-1]), path


def ed25519_seal(entry):
    priv = serialization.load_pem_private_key(
        open(os.path.join(KEYS, "audit_ed25519_private.pem"), "rb").read(), password=None)
    canonical = json.dumps(entry, sort_keys=True, separators=(",", ":")).encode()
    sig = priv.sign(canonical)
    pub = priv.public_key().public_bytes(serialization.Encoding.Raw, serialization.PublicFormat.Raw)
    Ed25519PublicKey.from_public_bytes(pub).verify(sig, canonical)
    out = os.path.join(HERE, "audit", "signed_audit.jsonl")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "a") as f:
        f.write(json.dumps({"audit_entry": entry, "seal": {"alg": "Ed25519",
                "signature": sig.hex(), "public_key": pub.hex()}}) + "\n")
    return sig.hex(), pub.hex(), out


def enforce(payload_path):
    payload = json.load(open(payload_path))
    print("=" * 74)
    print(f"ODGS ENFORCEMENT  |  process: {PROCESS_URN}")
    print(f"row ({os.path.basename(payload_path)}): {json.dumps(payload)}")
    print("-" * 74)
    interceptor = OdgsInterceptor(project_root_path=PROJECT)
    for rule in interceptor.rules.values():
        att = rule.get("__attestation__")
        if att:
            print(f"rule pack signature : VERIFIED ({att['issuer']}, key {att['key_id']})")
            break
    print(f"active rules loaded : {len(interceptor.rules)}")
    blocked = None
    try:
        interceptor.intercept(process_urn=PROCESS_URN, data_context=payload)
        print("\nVERDICT: APPROVED — all NOT NULL constraints satisfied")
    except ProcessBlockedException as e:
        blocked = str(e)
        print(f"\nVERDICT: BLOCKED — {blocked}")
    entry, log = last_engine_audit_entry()
    sig, pub, sealed = ed25519_seal(entry)
    print("-" * 74)
    print("AUDIT RECORD (engine-generated, tri-partite binding)")
    print(f"  event_id        : {entry['event_id']}")
    print(f"  verdict         : {entry['verdict']}")
    print(f"  payload_hash    : {entry['tri_partite_binding']['payload_hash']}")
    print(f"  definition_hash : {entry['tri_partite_binding']['definition_hash']}")
    if entry["violations"]:
        for v in entry["violations"]:
            print(f"  violation       : {v}")
    print(f"AUDIT SEAL (Ed25519, verified)  signature={sig[:32]}...")
    print(f"  sealed log      : {sealed}")
    print("=" * 74)
    return 1 if blocked else 0


if __name__ == "__main__":
    build_pack()
    print()
    sys.exit(enforce(sys.argv[1]))
